Repository teummeireo/ProfessorTooFast, pull requests merged in 2024-12, with the labels that each got.

#2 [add] 백엔드 초기 구조 설정
  .classpath
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  bin/main/webapp/META-INF/MANIFEST.MF
  bin/main/webapp/WEB-INF/web.xml
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/dao/UserDAO.class
  build/classes/com/ptf/servlet/DailyStatisticsServlet.class
  build/classes/com/ptf/servlet/LoginServlet.class
  build/classes/com/ptf/servlet/MonthlyStatisticsServlet.class
  build/classes/com/ptf/servlet/MySurveyServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/com/ptf/util/DBManager.class
  build/classes/com/ptf/util/OracleDBManager.class
  build/classes/com/ptf/vo/StatisticsVO.class
  build/classes/com/ptf/vo/SurveyVO.class
  build/classes/com/ptf/vo/UserVO.class
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/dao/UserDAO.java
  src/main/java/com/ptf/servlet/DailyStatisticsServlet.java
  src/main/java/com/ptf/servlet/LoginServlet.java
  src/main/java/com/ptf/servlet/MonthlyStatisticsServlet.java
  src/main/java/com/ptf/servlet/MySurveyServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/java/com/ptf/util/DBManager.java
  src/main/java/com/ptf/util/OracleDBManager.java
  src/main/java/com/ptf/vo/StatisticsVO.java
  src/main/java/com/ptf/vo/SurveyVO.java
  src/main/java/com/ptf/vo/UserVO.java
Labels: add ➕

#5 [feat] #3 DAO, VO 구현 완료
  .classpath
  .gitignore
  .settings/org.eclipse.wst.common.component
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/dao/UserDAO.class
  build/classes/com/ptf/util/PasswordUtil.class
  build/classes/com/ptf/vo/StatisticsVO.class
  build/classes/com/ptf/vo/SurveyVO.class
  build/classes/com/ptf/vo/UserVO$Role.class
  build/classes/com/ptf/vo/UserVO.class
  build/classes/mydb.properties
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/dao/UserDAO.java
  src/main/java/com/ptf/util/PasswordUtil.java
  src/main/java/com/ptf/vo/StatisticsVO.java
  src/main/java/com/ptf/vo/SurveyVO.java
  src/main/java/com/ptf/vo/UserVO.java
Labels: feat ✨

#12 [feat] #11 회원가입 로그인 로그아웃 백엔드 파트 구현 완료.
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/servlet/LoginServlet.class
  build/classes/com/ptf/servlet/LogoutServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/com/ptf/util/EncodingFilter.class
  build/classes/mydb.properties
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/servlet/LoginServlet.java
  src/main/java/com/ptf/servlet/LogoutServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/java/com/ptf/util/EncodingFilter.java
  src/main/webapp/WEB-INF/web.xml
Labels: feat ✨

#14 [feat] #13 유저정보조회, 아이디/닉네임 중복확인 서블릿 구현완료.
  .classpath
  build/classes/com/ptf/servlet/CheckLoginIdServlet.class
  build/classes/com/ptf/servlet/CheckNicknameServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/com/ptf/util/AuthenticationUtil.class
  build/classes/com/ptf/util/IsSubmitScheduler$1.class
  build/classes/com/ptf/util/IsSubmitScheduler.class
  build/classes/com/ptf/util/SessionUtil.class
  libs/javax.servlet-api-4.0.1.jar
  src/main/java/com/ptf/servlet/CheckLoginIdServlet.java
  src/main/java/com/ptf/servlet/CheckNicknameServlet.java
  src/main/java/com/ptf/servlet/LogoutServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/java/com/ptf/util/AuthenticationUtil.java
  src/main/java/com/ptf/util/IsSubmitScheduler.java
  src/main/java/com/ptf/util/SessionUtil.java
Labels: feat ✨

#16 [feat] my_survey.jsp 구현
  .project
  .settings/org.eclipse.wst.common.component
  build/classes/com/ptf/vo/PTFUserVO$Role.class
  build/classes/com/ptf/vo/PTFUserVO.class
  build/classes/com/ptf/vo/StatisticsVO.class
  build/classes/com/ptf/vo/SurveyVO.class
  build/classes/mydb.properties
  src/main/webapp/css/style.css
  src/main/webapp/css/styles.css
  src/main/webapp/login.jsp
  src/main/webapp/my_survey.jsp
  src/main/webapp/survey.jsp
Labels: feat ✨

#17 [feat] #15 설문 관련 서블릿 구현 완료.
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/servlet/CheckLoginIdServlet.class
  build/classes/com/ptf/servlet/CheckNicknameServlet.class
  build/classes/com/ptf/servlet/LoginServlet.class
  build/classes/com/ptf/servlet/MySurveyServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/com/ptf/util/AuthenticationUtil.class
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/servlet/CheckLoginIdServlet.java
  src/main/java/com/ptf/servlet/CheckNicknameServlet.java
  src/main/java/com/ptf/servlet/LoginServlet.java
  src/main/java/com/ptf/servlet/MySurveyServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/java/com/ptf/util/AuthenticationUtil.java
Labels: feat ✨

#24 Feature/#20 feat 프론트엔드 rest api 코드 설계
  build/classes/com/ptf/util/EncodingFilter.class
  src/main/java/com/ptf/util/EncodingFilter.java
  src/main/webapp/my_survey.jsp
  src/main/webapp/rest_imsi.jsp
Labels: feat ✨

#26 [feat] #22 survey.jsp 하단에 제출하기 눌렀을 때 Modal 추가
  build/classes/com/ptf/util/EncodingFilter.class
  src/main/java/com/ptf/util/EncodingFilter.java
  src/main/webapp/css/style.css
  src/main/webapp/survey.jsp
Labels: feat ✨

#30 [add] 리다이렉트 서블릿 생성 완료.
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/redirect/LoginPageServlet.class
  build/classes/com/ptf/servlet/redirect/MainPageServlet.class
  build/classes/com/ptf/servlet/redirect/MySurveyPageServlet.class
  build/classes/com/ptf/servlet/redirect/NewSurveyPageServlet.class
  build/classes/com/ptf/servlet/redirect/RegisterPageServlet.class
  build/classes/com/ptf/servlet/redirect/StatisticsPageServlet.class
  build/classes/mydb.properties
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/redirect/LoginPageServlet.java
  src/main/java/com/ptf/servlet/redirect/MainPageServlet.java
  src/main/java/com/ptf/servlet/redirect/MySurveyPageServlet.java
  src/main/java/com/ptf/servlet/redirect/NewSurveyPageServlet.java
  src/main/java/com/ptf/servlet/redirect/RegisterPageServlet.java
  src/main/java/com/ptf/servlet/redirect/StatisticsPageServlet.java
  src/main/webapp/main.jsp
Labels: add ➕

#33 [feat] #28 REST API 연결
  src/main/webapp/my_survey.jsp
  src/main/webapp/rest_imsi.jsp
  src/main/webapp/survey.jsp
Labels: feat ✨

#35 [add] #34 삭제 완료.
  .gitignore
  build/classes/mydb.properties
Labels: add ➕

#36 [feat] #32 Main 기초 작업
  src/main/webapp/main.jsp
Labels: feat ✨

#38 [feat] #37 로그인 회원가입 api연결완료
  src/main/webapp/images/survey_image.jpg
Labels: feat ✨

#41 [feat] #39 check 구현 완료.
  .settings/org.eclipse.wst.common.component
  build/classes/mydb.properties
  src/main/webapp/check_admin.jsp
  src/main/webapp/check_session.jsp
  src/main/webapp/check_user.jsp
  src/main/webapp/main.jsp
  src/main/webapp/my_survey.jsp
  src/main/webapp/statistics.jsp
  src/main/webapp/survey.jsp
Labels: feat ✨

#45 [feat] #44 로그인 비밀번호 복구완료
  src/main/webapp/css/login_register.css
  src/main/webapp/login.jsp
  src/main/webapp/register.jsp
Labels: feat ✨

#48 [mod] #43 코드 수정 완료
  build/classes/com/ptf/servlet/DailyStatisticsServlet.class
  build/classes/com/ptf/servlet/MySurveyServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  src/main/java/com/ptf/servlet/DailyStatisticsServlet.java
  src/main/java/com/ptf/servlet/MySurveyServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
Labels: mod 〰

#54 [feat] #53 내설문보기 구현완료.
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/servlet/MySurveyServlet.class
  build/classes/mydb.properties
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/servlet/MySurveyServlet.java
  src/main/webapp/rest_imsi.jsp
Labels: feat ✨

#56 Feature/#50 feat mainjsp 수정
  src/main/webapp/css/main_css.css
  src/main/webapp/css/style.css
  src/main/webapp/main.jsp
  src/main/webapp/rest_imsi.jsp
Labels: feat ✨

#58 [feat] #51 (유저)내설문 보기 페이지 구현
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/statistics_admin.jsp
  src/main/webapp/statistics_user.jsp
Labels: feat ✨
