Repository teummeireo/ProfessorTooFast, pull requests merged in 2025-01, with the labels that each got.

#59 [feat] #57 feat main.jsp 찐최종
  .gitignore
  .settings/org.eclipse.core.resources.prefs
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/mydb.properties
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/webapp/css/login_register.css
  src/main/webapp/css/main_css.css
  src/main/webapp/login.jsp
  src/main/webapp/main.jsp
  src/main/webapp/register.jsp
Labels: feat ✨

#61 [feat] #60 new 캐싱전략 필터 구현 완료.
  build/classes/com/ptf/util/SessionValidationFilter.class
  build/classes/mydb.properties
  src/main/java/com/ptf/util/SessionValidationFilter.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/main.jsp
Labels: feat ✨

#64 [feat] #62 알림시스템 구축 성공!
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/servlet/SseServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/redirect/MainPageServlet.class
  build/classes/com/ptf/servlet/redirect/StatisticsPageServlet.class
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/servlet/SseServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/redirect/MainPageServlet.java
  src/main/java/com/ptf/servlet/redirect/StatisticsPageServlet.java
  src/main/webapp/css/main_css.css
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/login.jsp
  src/main/webapp/main.jsp
  src/main/webapp/rest_imsi.jsp
  src/main/webapp/statistics_admin.jsp
  src/main/webapp/statistics_user.jsp
  src/main/webapp/survey.jsp
Labels: feat ✨

#68 [fix] #67 회원가입 오류수정
  .classpath
  .settings/org.eclipse.wst.common.component
  resources/fileupload.properties
  resources/mydb.properties
  src/main/webapp/register.jsp
Labels: fix 💥

#69 Mod/#65 mod qa 및 자잘한 코드 수정
  build/classes/com/ptf/servlet/SurveyServlet.class
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/check_admin.jsp
  src/main/webapp/check_user.jsp
  src/main/webapp/css/main_css.css
  src/main/webapp/css/my_survey_css.css
  src/main/webapp/login.jsp
  src/main/webapp/main.jsp
  src/main/webapp/my_survey.jsp
  src/main/webapp/register.jsp
  src/main/webapp/statistics_admin.jsp
  src/main/webapp/statistics_user.jsp
  src/main/webapp/survey.jsp
Labels: mod 〰

#72 [mod] #70 QA 완료.
  build/classes/com/ptf/servlet/CheckLoginIdServlet.class
  build/classes/com/ptf/servlet/CheckNicknameServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/fileupload.properties
  src/main/java/com/ptf/servlet/CheckLoginIdServlet.java
  src/main/java/com/ptf/servlet/CheckNicknameServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/webapp/css/login_register.css
  src/main/webapp/register.jsp
Labels: add ➕, mod 〰

#76 [add] #73 도커파일 추가완료
  .dockerignore
  .gitignore
  .project
  Dockerfile
  build/classes/fileupload.properties
  libs/jstl-1.2.jar
Labels: add ➕

#78 [chore] #77 resources 폴더 삭제 완료
  resources/fileupload.properties
  resources/mydb.properties
Labels: chore 🛠

#80 [mod] #79 dockerfile 수정완료
  Dockerfile
Labels: mod 〰

#82 [merge] #81 main에 develop 내용 병합(첫 배포)
  .classpath
  .dockerignore
  .github/workflows/deploy.yml
  .gitignore
  .project
  .settings/org.eclipse.wst.common.component
  Dockerfile
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/servlet/CheckLoginIdServlet.class
  build/classes/com/ptf/servlet/CheckNicknameServlet.class
  build/classes/com/ptf/servlet/MarkedDatesServlet.class
  build/classes/com/ptf/servlet/SseServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  build/classes/com/ptf/servlet/UserMarkedDatesServlet.class
  build/classes/com/ptf/servlet/UserServlet.class
  build/classes/com/ptf/servlet/redirect/MainPageServlet.class
  build/classes/com/ptf/servlet/redirect/StatisticsPageServlet.class
  build/classes/com/ptf/util/SessionValidationFilter.class
  build/classes/mydb.properties
  libs/jstl-1.2.jar
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/servlet/CheckLoginIdServlet.java
  src/main/java/com/ptf/servlet/CheckNicknameServlet.java
  src/main/java/com/ptf/servlet/MarkedDatesServlet.java
  src/main/java/com/ptf/servlet/SseServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/java/com/ptf/servlet/UserMarkedDatesServlet.java
  src/main/java/com/ptf/servlet/UserServlet.java
  src/main/java/com/ptf/servlet/redirect/MainPageServlet.java
  src/main/java/com/ptf/servlet/redirect/StatisticsPageServlet.java
  src/main/java/com/ptf/util/SessionValidationFilter.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/check_admin.jsp
  src/main/webapp/check_user.jsp
  src/main/webapp/css/login_register.css
  src/main/webapp/css/main_css.css
  src/main/webapp/css/my_survey_css.css
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/login.jsp
  src/main/webapp/main.jsp
  src/main/webapp/my_survey.jsp
  src/main/webapp/register.jsp
  src/main/webapp/rest_imsi.jsp
  src/main/webapp/statistics_admin.jsp
  src/main/webapp/statistics_user.jsp
  src/main/webapp/survey.jsp
Labels: merge 🔀

#85 [chore] #84 postgre 버전 수정 완료.
  .classpath
  .project
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/util/PostgreDBManager.class
  build/classes/mypostgre.properties
  libs/postgresql-42.6.0.jar
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/util/PostgreDBManager.java
  src/main/resources/mypostgre.properties
Labels: chore 🛠

#86 [chore] #84 postgre 버전 추가 수정 및 테스트 완료.
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
Labels: chore 🛠

#88 Merge/#87 merge postgresql 로 main 배포
  .classpath
  .project
  build/classes/com/ptf/dao/PTFUserDAO.class
  build/classes/com/ptf/dao/StatisticsDAO.class
  build/classes/com/ptf/dao/SurveyDAO.class
  build/classes/com/ptf/util/PostgreDBManager.class
  build/classes/mypostgre.properties
  libs/postgresql-42.6.0.jar
  src/main/java/com/ptf/dao/PTFUserDAO.java
  src/main/java/com/ptf/dao/StatisticsDAO.java
  src/main/java/com/ptf/dao/SurveyDAO.java
  src/main/java/com/ptf/util/PostgreDBManager.java
  src/main/resources/mypostgre.properties
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/statistics_admin.jsp
Labels: merge 🔀

#89 [merge] #87 mypostgre.properties 삭제 및 이그노어
  .gitignore
  Dockerfile
  build/classes/mypostgre.properties
  src/main/resources/mypostgre.properties
Labels: merge 🔀

#94 [feat] #91 main에 닉네임 추가
  src/main/webapp/css/main_css.css
  src/main/webapp/css/style.css
  src/main/webapp/main.jsp
Labels: feat ✨

#96 Merge/#87 merge postgresql 로 main 배포
  .gitignore
  Dockerfile
  build/classes/mypostgre.properties
  src/main/resources/mypostgre.properties
Labels: merge 🔀

#97 [add] #95 css 수정
  .classpath
  .settings/org.eclipse.wst.common.component
  src/main/webapp/css/my_survey_css.css
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/my_survey.jsp
  src/main/webapp/statistics_admin.jsp
Labels: add ➕

#99 [add] #98 close-button 클릭 시 모달 닫기
  src/main/webapp/css/style.css
  src/main/webapp/my_survey.jsp
Labels: add ➕

#104 [fix] #103 modal 해결
  src/main/webapp/survey.jsp
Labels: fix 💥

#106 [fix] #105 버튼 배경 삭제
  src/main/webapp/css/my_survey_css.css
Labels: fix 💥

#113 [mod] #110 코드 수정완료
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/webapp/check_user.jsp
  src/main/webapp/css/main_css.css
  src/main/webapp/css/my_survey_css.css
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/css/style.css
  src/main/webapp/error.jsp
  src/main/webapp/my_survey.jsp
  src/main/webapp/register.jsp
  src/main/webapp/statistics_admin.jsp
  src/main/webapp/survey.jsp
Labels: mod 〰

#115 [mod] #114 일별 통계 모달창 일부 수정
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/statistics_admin.jsp
Labels: mod 〰

#119 [feat] #118 develop(oracle)버전 커밋
  .gitignore
  src/main/webapp/main.jsp
  src/main/webapp/statistics_admin.jsp
Labels: feat ✨, merge 🔀

#123 [feat] #118 오늘 날짜 버그 진짜 수정완료.
  src/main/webapp/statistics_admin.jsp
Labels: feat ✨, merge 🔀

#124 [feat] #118 sse 알림 관련 오류 해결
  build/classes/com/ptf/servlet/SseServlet.class
  build/classes/com/ptf/servlet/SurveyServlet.class
  src/main/java/com/ptf/servlet/SseServlet.java
  src/main/java/com/ptf/servlet/SurveyServlet.java
Labels: feat ✨, merge 🔀

#125 [feat] #118 알림 css 복구완료.
  build/classes/com/ptf/servlet/SurveyServlet.class
  src/main/java/com/ptf/servlet/SurveyServlet.java
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/statistics_admin.jsp
Labels: feat ✨, merge 🔀

#126 [feat] #118 sse 진짜 버그 수정 완료.
  build/classes/com/ptf/servlet/SseServlet.class
  src/main/java/com/ptf/servlet/SseServlet.java
  src/main/webapp/css/statistics_admin.css
  src/main/webapp/statistics_admin.jsp
Labels: feat ✨, merge 🔀
